language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install tox-travis
  - pip install -U tox

script:
  - tox -e ci

notifications:
  email:
    on_success: change
    on_failure: change